version: '3'
services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mysql:/var/lib/mysql'
  redis:
    image: 'redis:alpine'
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - 'redis:/data'
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAIL_PORT}:1025'
    environment:
      VIRTUAL_HOST: 'mailhog.kingstondevelopers.test'
      VIRTUAL_PORT: 8025
volumes:
  mysql:
    driver: local
  redis:
    driver: local
