on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '*'

      - run: npx --yes @11ty/eleventy --input=./src --output=./dist

      - name: Publish
        if: github.event_name == 'push' && github.ref_name == 'main'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages publish ./dist --project-name=kingston-developers --commit-hash ${{ github.sha }} --commit-message "${{ github.event.head_commit.message }}"